name: Building LEAST GAME I MADE

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build NDS ROM
        run: make

      - name: Upload NDS
        uses: actions/upload-artifact@v4
        with:
          name: lowest-number-nds
          path: "*.nds"
          if-no-files-found: error


